apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmap-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmap-reader
subjects:
- kind: User
  name: "arn:aws:iam::533267166571:user/S1"  # Replace with your IAM user ARN
  apiGroup: rbac.authorization.k8s.io

