name: "Terraform"

on:
  push:
    branches:
      - infra

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0
          terraform_wrapper: false

      - name: configuration AWS credetials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Terraform Format
        run: terraform fmt 
        working-directory: ./eksTerra 

      - name: Terraform Init
        run: terraform init
        working-directory: ./eksTerra 

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./eksTerra 

    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve 