name: terraform workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

  push:
    branches:
      - infra
    paths-ignore:
      - helm/**
      - K8s/**
      - serverTerra/**
      - README.md
      - eksTerra/**
      - Jenkinsfile/*
      - infra/*
      

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0
          terraform_wrapper: false
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform Format
        run: terraform fmt
        working-directory: ./monitorTerraConfig
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./monitorTerraConfig
      
      - name: Terraform Destroy
        if: ${{github.event.inputs.action}} == 'destroy'
        run: terraform destroy --auto-approve 
        working-directory: ./monitorTerraConfig  
      
     
